# Generated by Django 5.2.6 on 2025-09-25 22:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcsFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='ical/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
