# Generated by Django 5.2.6 on 2025-10-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_subscription_user_whop_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bypass_token_limit',
            field=models.BooleanField(default=False),
        ),
    ]
